version: 2
updates:
  # Backend - .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kvaes"
    assignees:
      - "kvaes"
    commit-message:
      prefix: "chore(backend)"
      prefix-development: "chore(backend)"

  # Frontend - npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend/events-app"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kvaes"
    assignees:
      - "kvaes"
    commit-message:
      prefix: "chore(frontend)"
      prefix-development: "chore(frontend)"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kvaes"
    assignees:
      - "kvaes"
    commit-message:
      prefix: "chore(actions)"
      prefix-development: "chore(actions)"